### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by og900aero** [pirafrank/what-size.yazi#4]
After Yazi 4.0 version, get info message:

"The first paramtere of `entry()` has been replaced by the new `job` instead of the previous `args`.
Please use `job.args` instead `args` to access the arguments in your `what-size.yazi` plugin.
See #1966 for details: https://github.com/sxyazi/yazi/pull/1966"

**Comment by pirafrank** [comment]
Hi, v4.0 was released last week. I've yet to check changes. I planned to work on it during the holidays.

**Comment by pirafrank** [comment]
Fixed in 2780de5aeef1ed16d1973dd6e0cd4d630c900d56

**Comment by og900aero** [comment]
thx!
